language: node_js
cache:
  yarn: true
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
node_js:
  - '10'
script:
  - lerna run test
  - lerna run test:ci
after_success:
  - if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./publish.sh; fi
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
