language: node_js
cache:
  yarn: true
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
node_js:
  - '8'
script:
  - npm i -g clipped codecov istanbul
  - npm run build
  - istanbul cover ./node_modules/mocha/bin/_mocha  -- -R spec
  - codecov
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
