language: node_js
cache:
  yarn: true
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
node_js:
  - '8'
script:
  - npm i -g clipped codecov autopublish
  - npm test
  - codecov
  - npm run build
after_success:
  - npm run semantic-release
  - for d in presets/*; do autopublish "$d"; done
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
