language: node_js
cache:
  yarn: true
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
node_js:
  - '8'
script:
  - npm i -g clipped lerna autopublish
  - cd packages/clipped && npm run build && cd ../../ # Build clippped to use it in lerna run build
  - lerna run test
  - lerna run build
after_success:
  - if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./publish.sh; fi
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
